### ISSUE TITLE
widget request "lokesh pretty checkbox"

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/widgets#12]
https://lokesh-coder.github.io/pretty-checkbox/#basic-checkbox

from the https://github.com/surveyjs/editor/issues/232

**Comment by tsv2013** [comment]
I've added pretty-checkbox custom widget basic implementation. It works for checkboxes and radiobuttons with limited set of options. The widget inner markup highly depends on the certain pretty-checkbox options. This makes common implementation of this widget too complex IMO.

**Comment by tjtaojiang** [comment]
@tsv2013, I can't make your version of the widget to work for my case. I am not sure what I miss.

I attached a simplified version of my code, "suyveyjs-form.html" and "surveyjs-form.js" here: https://github.com/surveyjs/editor/issues/232, to show how it works for my case.

Please advise.

**Comment by tsv2013** [comment]
@tjtaojiang Sorry for delay. I've added example how to integrate pretty-checkbox custom widget. It resides on our site - https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=Angular2

As for your implementation of the custom widget - I cann't find binding between question value and the widget control.
I suggest you try to integrate our custom widgets pack into your application.
We'll provide you with the necessary support. Please feel free to contact us in case of any difficulties.

**Comment by tjtaojiang** [comment]
@tsv2013, binding by: row.value and row.text.  In my simplified code, you can run it and see the result.

**Comment by tjtaojiang** [comment]
@tsv2013, I noticed one thing, your <script src="https://unpkg.com/surveyjs-widgets"></script> alter the look and feel for the pretty checkbox.  Check https://lokesh-coder.github.io/pretty-checkbox/, and look for "Svg" and "Recurring" checkbox, it supposed to be curved.

**Comment by tjtaojiang** [comment]
@tsv2013, I copy your sample code from your link above and click "Edit in Plunker", for some reason, I still can't make your code to work.

I attached a simplified version from my implementation here for you to see how it work for me: 
[surveyjs_widget_for_pretty_checkbox.zip](https://github.com/surveyjs/widgets/files/1572791/surveyjs_widget_for_pretty_checkbox.zip).

To answer your previous concern, check row.value and row.text in the js, which I used for data binding.

I think my way has full control in term of custom widget. I just do not know if it will break some surveyjs process , like required filed property, etc.  I will keep testing.

Any advise is much appreciated.

**Comment by tjtaojiang** [comment]
@tsv2013, I noticed a very big bug in your recent changes.

All other types are blocked from addCustomWidget, except "radiogroup" and "checkbox". In other words, in "isFit:", you can only see "radiogroup" and "checkbox" type, other types like "text" will be blocked.

I think you need to fix this issue.

**Comment by tsv2013** [comment]
@tjtaojiang On this page (https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=Angular2) you can find the "Edit in Plunker" button. In this case our site creates a new "ready to run" plunk containing the current sample code.

E.g. after I clicked this button I've got the following plunk with the pretty-checkbox example for angular platform:
https://plnkr.co/edit/chHf8x?p=preview

It works for me ok.
Does this plunk work for you?

**Comment by tsv2013** [comment]
@tjtaojiang In the sampe plunk - https://plnkr.co/edit/chHf8x?p=preview
the following lines from the index.html files are responsible for adding the "pretty-checkbox" custom widget functionality:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css"/>
<script src="https://unpkg.com/surveyjs-widgets"></script>
```
because of the code of our "pretty-checkbox" custom widget implementation is resides in the "https://unpkg.com/surveyjs-widgets" script.

**Comment by tsv2013** [comment]
@tjtaojiang I've also created a plunk with the code you sent me in the "surveyjs_widget_for_pretty_checkbox.zip" archive.

This is the link to the plunk with your code - https://plnkr.co/edit/e3uqCK?p=preview
We can use this plunk as a starting point for the further discussion.

**Note** that I've commented reference to our custom widgets package (in the index.html file) because you are using your own implementation of the "pretty-checkbox" custom widget:
```
    <!--<script src="https://unpkg.com/surveyjs-widgets@0.98.4/surveyjs-widgets.js" type="text/javascript"></script>-->
```

Could you check this plunk also?

**Comment by tsv2013** [comment]
My thoughts about the pretty-checkbox cutom widget implementation

"pretty-checkbox" is the CSS library and requires different markup for different features.
This makes us to drop our default-generated markup of the "checkbox", "radiogroup" (and that much more worse the "matrix") questions and replace it with the markup required to make "pretty-checkbox" work properly.
If we remove our default markup, we become responsible for
- the two-way binding of the custom widget: subscribe on the question value changes and reflect them in the UI, and subscribe the UI control input and pass entered values to the question;
- the whole SurveyJS question functionality as read-only behaviour, "other item", "column count" and other options

Our basic implementation of the "pretty-checkbox" custom widget at this moment contains basic options and binding functionality and supports "checkbox" and "radiogroup" quesions only.

The full functionality can be added to the certain custom widget implementation by the united efforts of the SurveyJS team and the community. I hope on your understanding and support.

**Comment by tjtaojiang** [comment]
@tsv2013, for some reason, this Plunker version does not work when I copy them into my local: https://plnkr.co/edit/?p=preview. I still see the old radio and checkbox.

**Comment by tjtaojiang** [comment]
@tsv2013, for some reason, this Plunker version does not work when I copy them into my local: https://plnkr.co/edit/chHf8x?p=preview. I still see the old radio and checkbox.

**Comment by tsv2013** [comment]
@tjtaojiang Could you tell me whether the plunker https://plnkr.co/edit/chHf8x?p=preview works for you or not?

**Comment by dmitrykurmanov** [comment]
@tjtaojiang hello! Could you please describe your use case? Does the example in our site looks good? Do your problem with integrate widget in your project or with widget functionality?

**Comment by tjtaojiang** [comment]
@dmitrykurmanov, as I mentioned above, I copy three files in https://plnkr.co/edit/chHf8x?p=preview into my local, because some websites are blocked by my company, I need to use https://go.weblife.io to download all blocked css and js into my local.  I attach zip file contain all three I modified and used in my local.  You can see duplicated due to the websites are block and I have downloaded.  After I put all three in one directory and click html, I still only see the default (old fashion) radio and checkbox.

**Comment by tjtaojiang** [comment]
@dmitrykurmanov, as I mentioned above, I copy three files in https://plnkr.co/edit/chHf8x?p=preview into my local, because some websites are blocked by my company, I need to use https://go.weblife.io to download all blocked css and js into my local. I attach zip file contain all three I modified and used in my local. You can see duplicated due to the websites are block and I have downloaded. After I put all three in one directory and click html, I still only see the default (old fashion) radio and checkbox.
[test-surveyjs-form.zip](https://github.com/surveyjs/widgets/files/1576057/test-surveyjs-form.zip)

**Comment by tjtaojiang** [comment]
Hi, @dmitrykurmanov, @tsv2013,

After getting the sample code from https://plnkr.co/edit/chHf8x?p=preview, I do see the default checkbox and radiogroup are changed to pretty checkbox.

But at least I noticed those issues:

(1). You have modified the default checkbox to a square shaped pretty checkbox. If I need other shapes like "Svg" -> "Recurring", a curve shape checkbox, on https://lokesh-coder.github.io/pretty-checkbox/, or if I need to use the old square checkbox, I still need to create a custom widget, which is actually what users will need: how to create custom widget to cope their requests.

(2). Your new implementation deactivate colCount. Check your sample case.

(3). https://unpkg.com/surveyjs-widgets, or actually https://unpkg.com/surveyjs-widgets@0.98.4/surveyjs-widgets.js, has disabled any custom widget implementation. Uncomment addCustomWidgetForDatePicker() in test-surveyjs-forms.js in my attachment:
[test surveyjs widget.zip](https://github.com/surveyjs/widgets/files/1576799/test.surveyjs.widget.zip)
 , you will see isFit: never gets called.

(4). For lengthy label radio or checkbox, the current pretty checkbox cuts the total description. Check my attachment above.

**Comment by tsv2013** [comment]
@tjtaojiang Answering your questions:

(1) - I've implemented "addOn" feature for the "pretty-checkbox" custom widget. It allows to insert any additional markup before the "label" tag

For "SVG" mode you will need to add the following code:
```JavaScript
  var prettyCheckbox = Survey.CustomWidgetCollection.Instance.getCustomWidgetByName(
    "pretty-checkbox"
  );
  var checkboxSettings = prettyCheckbox.widgetJson.settings.checkbox;
  checkboxSettings.rootClass = "pretty p-svg p-curve";
  checkboxSettings.addOn =
    "<!-- svg path -->" +
    '<svg class="svg svg-icon" viewBox="0 0 20 20">' +
    '<path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;">' +
    "</path>" +
    "</svg>";
```

(2) I've implemented the "colCount" feature

(3) I've checked different custom widgets (including the "pretty-checkbox") on the same page of a survey - they all works fine for me.
I've checked the last code you sent us and found that you commented your custom widget initialization function:
```JavaScript
function onAngularComponentInit() {
    // addCustomWidgetForDatePicker();
    Survey.SurveyNG.render("surveyElement", {model: survey});
}
```
After I've uncommented this call, everything works ok for me.

(4) I've checked your attachment, and see that long item descriptions are not trimmed. At this point I'd like to clarify - what behaviour for the long item descriptions is suitable for you? Could you share a screenshot or drawing with desired view.

**Comment by tsv2013** [comment]
@tjtaojiang The changes mentioned above will be available since 0.98.6. For more details you can check the 0d7f9b9195ee6a07cc578981e4ec54cb48b26341 commit.

**Comment by tjtaojiang** [comment]
Hi @tsv2013,

(1). Due to the (2) - (3), I can't test this: "If I need other shapes like "Svg" -> "Recurring", a curve shape checkbox, on https://lokesh-coder.github.io/pretty-checkbox/, or if I need to use the old square checkbox..."

(2). colCount is still not working. I attach my code here for reference 
[test surveyjs widget.zip](https://github.com/surveyjs/widgets/files/1580348/test.surveyjs.widget.zip). You can check the attached image file, test-surveyjs-form.jpg .

(3).  Check my attachment above, https://unpkg.com/surveyjs-widgets, or actually now: https://unpkg.com/surveyjs-widgets@0.98.5/surveyjs-widgets.js, still disable radiogroup and checkbox. Much worse, in my real code (not attached), it disables any custom widget implementation.

(4). Check the attached image file, lengthy label still stretch out and trimmed.

**Comment by tsv2013** [comment]
@tjtaojiang

As I wrote in this comment (https://github.com/surveyjs/widgets/issues/12#issuecomment-353289703) - "The changes mentioned above will be available since 0.98.6". After 0.98.6 will be released, you will be able to try "addOn" feature and "colCount" option. I'll also add corresponding demo on our site.

As for (3) - I'm not able to reproduce this issue on my side. Can you prepare an example in plunker or any other sandbox or project or github repo? So I will be able to reproduce the issue and fix it.

(4) - I do understand that things are not so good as they can be. But could you give your opinion - how it should be fixed?

**Comment by tsv2013** [comment]
@tjtaojiang I've checked your code and screenshot you sent. And I can say that `datePickerWidget` is applied on your page. You see an empty space instead of date picker control because you disable default rendering via setting the `isDefaultRender: false` option and nothing created in the `afterRender: function (question, el) {
        }` function as I can see from your custom `datePickerWidget` code from your file:

```
function addCustomWidgetForDatePicker() {
    var datePickerWidget = {
        isFit: function (question) {
            alert("question = |" + question + "|\n"
                + "question.getType() = |" + question.getType() + "|\n"
                + "question.inputType = |" + question.inputType + "|\n"
                + "question.class = |" + question.class + "|\n"
                + "question.name = |" + question.name + "|\n"
                + "question.title = |" + question.title + "|\n"
            );
            return (question.getType() === 'text') && (question.inputType === 'date');
        },
        isDefaultRender: false,
        afterRender: function (question, el) {
        }
    };

    Survey.CustomWidgetCollection.Instance.addCustomWidget(datePickerWidget);
}
```

**Comment by tsv2013** [comment]
@tjtaojiang In order to use custom widgets, their code sould be loaded after the core SurveyJS library:

```
    <script src="https://surveyjs.azureedge.net/0.98.5/survey.angular.js" type="text/javascript"></script>
    <script src="https://unpkg.com/surveyjs-widgets@0.98.5/surveyjs-widgets.js" type="text/javascript"></script>
```

**Comment by tjtaojiang** [comment]
@tsv2013,

Refer to your: "As for (3) - I'm not able to reproduce this issue on my side. Can you prepare an example in plunker or any other sandbox or project or github repo? So I will be able to reproduce the issue and fix it."

Please use my previous zip file, test surveyjs widget.zip, the 4th post above this one, click test-surveyjs-form.html after you unzip.  You can see radio and checkbox element never got passed into isFit: in addCustomWidgetForDatePicker() .

I will post another post to illustrate how do I cope my issues (10 - (4) next.

**Comment by tjtaojiang** [comment]
Hi @tsv2013 and @dmitrykurmanov,

Here is how I solve my issues from (1) - (4).  I need to comment out , otherwise it will disable all custom widget I created, as I mentioned before.

Here is the attachement for it: 
[test surveyjs widget-3.zip](https://github.com/surveyjs/widgets/files/1580800/test.surveyjs.widget-3.zip)

click test-surveyjs-form.html after you unzip it.

I am not sure my way will introduce any other issues, which may break some calculation and dependency, like required property etc.

Please offer advise.

**Comment by tjtaojiang** [comment]
Hi @tsv2013 and @dmitrykurmanov,

Here is how I solve my issues from (1) - (4). You need to comment out https://unpkg.com/surveyjs-widgets@0.98.5/surveyjs-widgets.js as in test-surveyjs-form.html, otherwise it will disable all custom widget I created, as I mentioned before.

Here is the attachement for it: 
[test surveyjs widget-3.zip](https://github.com/surveyjs/widgets/files/1580810/test.surveyjs.widget-3.zip)
, click test-surveyjs-form.html after you unzip it.

I am not sure if my code will introduce any other issues, which may break some surveyjs calculation and dependency, like required property etc. 

Please offer advise.

**Comment by tsv2013** [comment]
@tjtaojiang  The "radio and checkbox element never got passed into `isFit` in `addCustomWidgetForDatePicker()`" because they are already fit for another custom widget. It is hard to apply two custom widgets on the same question. This can lead to unexpected side effects.

But until now our pretty-checkbox custom widget was activated always by question type if pretty-checkbox css styles were loaded on the page. I've changed this behaviour to activation by property: `renderAs` that should be set to "prettycheckbox" value.

As for your implementation of the pretty-checkbox custom widgets. Your certain implementation can better be suitable for solving your certain tasks. I don't see any problems in your implementation for now except of absence of two-way bindings: UI will not updated in case of model has been changed and choosen in UI values are not passed in the model. The last problem is crucial because if you choose some items and press `Complete` button you will see validation complains "Please answer the question." because the values you have choosen haven't been stored in the question.

**Comment by tjtaojiang** [comment]
@tsv2013, I will look into the two-way bindings issue you mentioned.

As far as "radio and checkbox" are already fit for another custom widget, then user will not be able to create a widget for their requirement?  This may not be a good idea. Can we remove the limit?

**Comment by tjtaojiang** [comment]
@tsv2013, I will look into the two-way bindings issue you mentioned. Do you have any recommendation how should I modify my implementation to cope with the issue?

As far as "radio and checkbox" are already fit for another custom widget, then user will not be able to create a widget for their requirement? This may not be a good idea. Can we remove the limit?

**Comment by tjtaojiang** [comment]
Hi @tsv2013 and @dmitrykurmanov,

Here is my current version which will fix two-way bindings issue. It also contains a custom widget for a date picker (pikaday object): 
[test surveyjs widget-4.zip](https://github.com/surveyjs/widgets/files/1583690/test.surveyjs.widget-4.zip). If you wish, I can move the date picker (pikaday object) custom widget to a separate thread.

But there is a minor issue which I have not figured out.  For some reason, the checkbox does not show the white check sign inside the checkbox. Do you know why?

I will be on vacation. I won't reply to you until I come back.  Thanks.

**Comment by tjtaojiang** [comment]
Hi @tsv2013 and @dmitrykurmanov,

Here is my current version which will fix two-way bindings issue. It also contains a custom widget for a date picker (pikaday object): 
[test surveyjs widget-4.zip](https://github.com/surveyjs/widgets/files/1583711/test.surveyjs.widget-4.zip)
. If you prefer, I can move the date picker (pikaday object) custom widget to a separate thread.

But there is a minor issue which I have not figured out. For some reason, the checkbox does not show the white check sign inside the checkbox. Do you know why?

I will be on vacation. I won't be able to reply to you until I come back. Thanks.

**Comment by tjtaojiang** [comment]
Please let me know if you can fix the issue that the checkbox does not show the white check sign inside the checkbox.

**Comment by tsv2013** [comment]
@tjtaojiang Can you check this plunker - https://plnkr.co/edit/VgOcR9?p=preview
Does it fit your requirements?

**Comment by tsv2013** [comment]
@tjtaojiang I guess you were talking about your code. I took a look, but I could not find in your code why the `path` object is of 0x0 size.

**Comment by tjtaojiang** [comment]
@tsv2013,

I guess it was two weeks ago.  Too many progress has been made. I will sum up the current situation to clear things out:

First of all, path data was not the issue. I have checked.

Your implementation will not be able to handle lengthy checkbox label, and I can't use it for that matter.

In my current implementation. Everything are handled, including two-way bindings you pointed out, except a minor issue here: the white check sign will not show up in the green checkbox in my most recent implementation. I attached my test code here for your reference: 
[test surveyjs widget-5.zip](https://github.com/surveyjs/widgets/files/1601322/test.surveyjs.widget-5.zip)

In test-surveyjs-form.js, if you UN-comment out addCustomWidgetForPrettyCheckbox_show_white_check() on line 42, but comment out addCustomWidgetForPrettyCheckbox_not_show_white_check() on line43, the white check sign WILL show up in the the green checkbox.

I guess there are some issues which use the way in addCustomWidgetForPrettyCheckbox_not_show_white_check(), where two-way bindings is handled but 
setAttribute() is used for setting up HTML objects.  This, somehow, prevent the white check sign to show up.  I guess the library for pretty-checkbox may not handle it correctly.
